version: "3"

networks:
  prefect_testing:
    external: false

services:
  influxdb:
    image: influxdb:2.0.7
    container_name: influxdb
    restart: always
    networks: [ prefect_testing ]
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: user
      DOCKER_INFLUXDB_INIT_PASSWORD: password
      DOCKER_INFLUXDB_INIT_ORG: testing
      DOCKER_INFLUXDB_INIT_BUCKET: metrics
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: tJ4kEsKUAQ7i6zFj87siUwTI4dyVFR2M0B_SqT22pSo5C83KZb7a43Vg-ZjeSiphSwZ6KMA5bL4Vr0xRGnE1dQ==
