name: Register workflows
on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Register flows
      env: # Or as an environment variable
        PREFECT_TOKEN: ${{ secrets.PREFECT_TOKEN }}
      run: |
        prefect auth login -t $PREFECT_TOKEN
        prefect register --project tutorial -p . -l github-flows
